services:
    app:
        build: ./
        ports:
            - "5173:5173"
        volumes:
            - ./src:/app/src
            - ./public:/app/public
        command: npm run dev
        container_name: ztransfer_app
        restart: unless-stopped
        environment:
            - CHOKIDAR_USEPOLLING=true
