name: vitest-and-docker-ci

on: push

jobs:
    test-front:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Install pnpm run tests
              run: npm add -g pnpm && pnpm install && pnpm test:ci
    docker:
        needs: test-front
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set docker image tag name
              shell: bash
              run: echo "tag=$(if [ ${{ steps.extract_branch.outputs.branch }} == 'main' ]; then echo 'latest'; else echo ${{ steps.extract_branch.outputs.branch }}; fi)" >>$GITHUB_OUTPUT
              id: set_tag
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  context: '{{defaultContext}}'
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/2209-wns-hopper-leszanes-back:${{ steps.set_tag.outputs.tag }}
